[colors.primary]
background = "#121212"
foreground = "#bebebe"

[colors.cursor]
text = "#121212"
cursor = "#eaeaea"

[colors.vi_mode_cursor]
text = "#121212"
cursor = "#eaeaea"

[colors.search.matches]
foreground = "#121212"
background = "#b91c1c"

[colors.search.focused_match]
foreground = "#121212"
background = "#D35F5F"

[colors.footer_bar]
foreground = "#121212"
background = "#bebebe"

[colors.selection]
text = "#bebebe"
background = "#333333"

[colors.normal]
black = "#333333"
red = "#D35F5F"
green = "#FFC107"
yellow = "#b91c1c"
blue = "#e68e0d"
magenta = "#D35F5F"
cyan = "#bebebe"
white = "#bebebe"

[colors.bright]
black = "#8a8a8d"
red = "#B91C1C"
green = "#FFC107"
yellow = "#b90a0a"
blue = "#f59e0b"
magenta = "#B91C1C"
cyan = "#eaeaea"
white = "#ffffff"
